Repository DigitalHolography/Holovibes, pull requests merged in 2024-07, with the labels that each got.

#442 Light UI visual improvement
  Holovibes/includes/gui/windows/lightui.hh
  Holovibes/includes/gui/windows/panels/info_panel.hh
  Holovibes/lightui.ui
  Holovibes/mainwindow.ui
  Holovibes/sources/gui/windows/MainWindow.cc
  Holovibes/sources/gui/windows/lightui.cc
  Holovibes/sources/gui/windows/panels/export_panel.cc
  Holovibes/sources/gui/windows/panels/info_panel.cc
Labels: enhancement

#447 [ENHANCEMENT] Record path improvement
  Holovibes/includes/gui/windows/lightui.hh
  Holovibes/includes/gui/windows/panels/export_panel.hh
  Holovibes/lightui.ui
  Holovibes/mainwindow.ui
  Holovibes/sources/gui/windows/MainWindow.cc
  Holovibes/sources/gui/windows/lightui.cc
  Holovibes/sources/gui/windows/panels/export_panel.cc
  Holovibes/sources/gui/windows/panels/info_panel.cc
  Holovibes/sources/tools/tools.cc
Labels: enhancement

#450 Fix z spinbox
  Holovibes/mainwindow.ui
  Holovibes/sources/gui/windows/lightui.cc
  Holovibes/sources/gui/windows/panels/image_rendering_panel.cc
Labels: bug

#454 Date in export name + file name smart reading
  Holovibes/includes/gui/windows/lightui.hh
  Holovibes/mainwindow.ui
  Holovibes/sources/API.cc
  Holovibes/sources/gui/windows/lightui.cc
  Holovibes/sources/gui/windows/panels/export_panel.cc
  Holovibes/sources/thread/frame_record_worker.cc
  Holovibes/sources/tools/tools.cc
Labels: enhancement

#458 LightUI: fixed "Idle" record progress bar state
  Holovibes/includes/gui/windows/lightui.hh
  Holovibes/includes/gui/windows/panels/info_panel.hh
  Holovibes/sources/gui/windows/lightui.cc
  Holovibes/sources/gui/windows/panels/export_panel.cc
  Holovibes/sources/gui/windows/panels/info_panel.cc
Labels: bug, refacto

#463 Added preset button in ConfigUI
  CHANGELOG.md
  Holovibes/includes/gui/windows/MainWindow.hh
  Holovibes/mainwindow.ui
  Holovibes/sources/gui/windows/MainWindow.cc
Labels: enhancement

#462 load file gpu preset application
  CHANGELOG.md
  Camera/configs/ametek_s710_euresys_coaxlink_octo.ini
  Camera/configs/ametek_s711_euresys_coaxlink_qsfp+.ini
  Holovibes/CMakeLists.txt
  Holovibes/includes/API.hh
  Holovibes/includes/gui/windows/MainWindow.hh
  Holovibes/sources/compute_settings.cc
  Holovibes/sources/gui/windows/MainWindow.cc
  Holovibes/sources/gui/windows/panels/import_panel.cc
  Preset/FILE_ON_GPU.json
Labels: enhancement

#461 date prefix sometime overwriting file resolved
  Holovibes/sources/tools/tools.cc
Labels: bug
